### ISSUE TITLE
Plugin/Documentation Search

### ISSUE THREAD

**Issue by ChristianMurphy** [unifiedjs/unifiedjs.github.io#12]
### Subject of the feature

Add a view dedicated to searching unified ecosystem plugins.
Potentially similar to:
* https://www.gatsbyjs.org/plugins
* https://apereo.github.io/cas/6.0.x/index.html

### Problem

The unified collective is de-centralized, across several organizations, and across hundreds of repositories.
New users are having trouble finding the documentation, and are often resorting to opening issues or asking in spectrum chat to track down where the docs are.

For example: [1](https://spectrum.chat/unified/syntax-tree/how-to-convert-nlcst-to-hast-or-html~882bcfe6-43d6-4f3f-94a5-fc433d9d6637), [2](https://spectrum.chat/unified/remark/how-to-use-remark-from-the-command-line~21e25220-d820-4b2e-a19a-137874794999), [3](https://github.com/remarkjs/remark/issues/445), [4](https://github.com/remarkjs/remark/issues/385), [5](https://spectrum.chat/unified/remark/remark-highlight-words~ef2aecd7-a3d7-40b4-8ea3-e25e44308234), [6](https://spectrum.chat/unified/unified/how-can-i-look-at-a-hast-and-or-save-it-as-a-file~e6c45aec-0154-47bb-9992-f126089b15a2), [7](https://spectrum.chat/unified/type-definitions/how-to-get-hast-element-type-definition~f16a9774-f826-410a-9e2b-d7dd0701f9bd), [8](https://spectrum.chat/unified/syntax-tree/hello-wheres-html-to-hast~151ae5d3-97d9-49fe-a2af-f986149cf859), [9](https://spectrum.chat/unified/remark/use-remark-plugin-to-add-frontmatter-properties~6313c15c-28a9-40f6-b17e-0192593dbed6), [10](https://spectrum.chat/unified/remark/how-can-i-lint-stringify-recursively-through-a-directory~6e40d546-4b66-460e-8b84-6bb858706c12), and many more

### Expected behaviour

Many (if not most) use cases are documented somewhere in the collective.
Users should be presented with an aggregated and search-able view of the existing documentation.

### Possible technologies

**Open Source**

* https://lucene.apache.org/solr
* https://www.elastic.co/products/elasticsearch
* http://sphinxsearch.com
* https://github.com/asciimoo/searx

**Proprietary Services**

* https://www.algolia.com
* https://cse.google.com/cse
* https://azure.microsoft.com/en-us/services/cognitive-services/bing-custom-search
* https://aws.amazon.com/cloudsearch

### Alternatives

* Centralize the documentation
* Other ideas, are welcome!

**Comment by wooorm** [comment]
Yeah that would be great, super useful!

**Comment by Murderlon** [comment]
I have been thinking about this as well and agree that this would be super helpful.

**Comment by tomByrer** [comment]
I leans towards centralizing the docs.  Likely easiest to keep the repos where they are, & aggregate them into 1 clump to possess as  HTML output.

Would be helpful either way, feels like a maze trying to find how to do stuff.  Even finding good tutorials via Google is hard.

**Comment by wooorm** [comment]
Most of this is done with the current release of the website, where it is possible to browse and search through packages/keywords/projects/topics.

The whole search functionality, including about 400 packages and 250 projects, fits in about 80kb minzipped. Everything is indexed client-side on `/explore/`, which is a bit of a performance hit but I don‘t think it’s very noticeable.

I’m kinda happy that we don’t use an external service, free or paid, to index everything, and to make the whole site completely static (`/explore/` is usable without JS as well).

If anyone finds bugs with search, do let me know!
