### ISSUE TITLE
Typo: Change 

### ISSUE THREAD

**Issue by capndave** [unifiedjs/unifiedjs.github.io#29]
### Subject of the issue

Describe your issue here.

This is *not* a place to ask questions.  For that, go to [spectrum](https://spectrum.chat/unified)

### Your environment

*   **OS**: 
*   **Packages**: 
*   **Env**: 

### Steps to reproduce

Tell us how to reproduce this issue.  Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behavior

What should happen?

### Actual behavior

What happens instead?

**Comment by ChristianMurphy** [comment]
Was this accidentally opened and #30 is the real issue?
If not could you add details to this issue?

**Comment by capndave** [comment]
Oops. Correct. #30 is the real issue
