### ISSUE TITLE
crusty code examples

### ISSUE THREAD

**Issue by tomByrer** [unifiedjs/unifiedjs.github.io#33]
### Subject of the feature

Examples are not standardized; & use older JS standards

### Problem

Using
`var rehype = require('rehype')`
has mostly been supplanted by 
`const rehype = require('rehype')`
I'm not sure if everyone is ready for ESModules yet; there is still some friction, but maybe that option should be listed also?

& this is only 1 example.  It is *very* confusing to me to see many ways this system can be syntaxed; I'd rather just see 1 way that is harmonized thoughout all codebases & docs.

**Comment by ChristianMurphy** [comment]
related to https://github.com/unifiedjs/rfcs/pull/4

**Comment by wooorm** [comment]
> I'd rather just see 1 way that is harmonized thoughout all codebases & docs

Isn’t that kinda how it currently is: everything uses vars and requires. Except that you’d like to use newer syntax?

**Comment by wooorm** [comment]
Gonna close this. I think the whole of unified, hundreds of projects, uses a pretty strict and very consistent code style, so I don’t get how you come to “It is very confusing to me to see many ways this system can be syntaxed; I'd rather just see 1 way that is harmonized thoughout all codebases & docs”, I think that’s the case currently.

Whether to use const or var, or cjs or esm, are different issues
