### ISSUE TITLE
Guides using deprecated library

### ISSUE THREAD

**Issue by a2k42** [unifiedjs/unifiedjs.github.io#39]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast

### Steps to reproduce

Guides such as [syntax-trees-typescript](https://unifiedjs.com/learn/guide/syntax-trees-typescript/) use the [mdast](https://www.npmjs.com/package/mdast) library which is deprecated.

Following the guide will result in warnings that the package is deprecated.

### Expected behavior

Guides show you how to get started with the unified ecosystem and do not result in deprecated warnings.

### Actual behavior

deprecated warnings

### Affected runtime and version

all

### Affected package manager and version

all

### Affected OS and version

all

**Comment by remcohaszing** [comment]
They use the `@types/mdast` package, not `mdast`. `@types/mdast` isn’t deprecated.
