### ISSUE TITLE
HTTPS certificate on unifiedjs.com expired

### ISSUE THREAD

**Issue by about-code** [unifiedjs/unifiedjs.github.io#41]
### Initial checklist

- [X] I read the [support docs](https://github.com/unifiedjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/unifiedjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/unifiedjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aunifiedjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

all (docs)

### Link to runnable example

https://unifiedjs.com

### Steps to reproduce

1. Visit https://unifiedjs.com.
2. See browser warning.

### Expected behavior

No browser warning. Valid HTTPS certificate.

### Actual behavior

Firefox Browser warns: "Potential security risk ahead" (since April 25th, 2023)

### Affected runtime and version

none

### Affected package manager and version

none

### Affected OS and version

all

**Comment by saibotsivad** [comment]
I pinged a couple people on Twitter (before I found this repo) hopefully one of them will notice soon 🙏

**Comment by wooorm** [comment]
I dunno what’s up. We use GH pages. Which does the HTTPS and Let’s Encrypt stuff.

**Comment by wooorm** [comment]
Thanks for the report. Works again. I toggled the custom domain off and on. And apparently that triggered GH to fix the certification.
